name: Convert to json

runs:
  using: 'composite'
  steps:
    - run: |
        cd Sparked.Csv2FhirMapping/ &&
        declare resources=(
          "Patient"
          "Organization"
          "Location"
          "Practitioner"
          "PractitionerRole"
          "Encounter"
          "AllergyIntolerance"
          "Condition"
          "Immunization"
          "Observation"
          "Procedure"
          "Medication"
          "MedicationRequest") &&\
        for resource in "${resources[@]}"
        do
        echo $resource && /tmp/Csv2FhirMapping-linux-x64-binaries/Csv2Fhir $resource "../testdata-csv/AU Core Sample Data - ${resource}.csv" ../generated/
        done
 
