name: Validate

on:
  pull_request


jobs:
  Convert:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Install .net deps
      uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages:
          libicu-dev
          unzip
          default-jdk
        execute_install_scripts: true
    - run: |
        cd /tmp &&\
        wget https://github.com/hl7au/au-fhir-test-data-utils/releases/latest/download/Csv2FhirMapping-linux-x64.zip &&\
        unzip Csv2FhirMapping-linux-x64.zip &&\
        chmod +x Csv2FhirMapping-linux-x64-binaries/Csv2Fhir
    - run: |
        cd Sparked.Csv2FhirMapping/ &&
        declare resources=(
          "Patient"
          "Organization"
          "Location"
          "Practitioner"
          "PractitionerRole"
          "Encounter"
          "AllergyIntolerance"
          "Condition"
          "Immunization"
          "Observation"
          "Procedure"
          "Medication"
          "MedicationRequest") &&\
        for resource in "${resources[@]}"
        do
        echo $resource && /tmp/Csv2FhirMapping-linux-x64-binaries/Csv2Fhir $resource "../testdata-csv/AU Core Sample Data - ${resource}.csv" ../generated/
        done
    - uses: GrantBirki/git-diff-action@v2.6.1
      id: git-diff-action
    - if: steps.git-diff-action.outputs.raw-diff != ''
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: Update generated files
    - run: wget https://github.com/hapifhir/org.hl7.fhir.core/releases/latest/download/validator_cli.jar
    - run: |
        java -jar validator_cli.jar generated/*.json \
             -version 4.0.1 -tx https://tx.dev.hl7.org.au/fhir \
             -ig hl7.fhir.au.core#0.4.0-preview  -sct au \
             -level errors -jurisdiction au \
             -html-output g_validation.html -output g_validation.xml
    - id: validation-result
      name: Archive validation result
      uses: actions/upload-artifact@v4
      with:
        name: validation-result
        path: g_validation.html
    - name: Show validation results
      uses: actions/github-script@v7
      with:
        script: |
          const comment = `
            Validation report: [${{ steps.validation-result.outputs.artifact-id }}](${{ steps.validation-result.outputs.artifact-url }})
          `;
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: comment
          })
